lowercaseOutputName: true
rules:
- pattern: java.lang<type=(.*)>
#- pattern: application(.*)
#- pattern: application<type=(.*)>
#- pattern: kafka.streams.*
- pattern: "application<type=streams><>(.+): (.+)__(.+)"
  name: application_streams
  value: 1
  labels:
    task_id: $1
    sources: $2
    sinks: $3
- pattern: kafka.streams<type=stream-record-cache-metrics, thread-id=(.+), task-id=(.+)_(.+), record-cache-id=(.+)><>(.+):.+
  name: kafka_streams_stream_record_cache_metrics
  labels:
    thread_id: "$1"
    task_id: "$2"
    partition_id: "$3"
    record-cache-id: "$4"
    metric: "$5"
- pattern: kafka.streams<type=stream-state-metrics, thread-id=(.+), task-id=(.+)_(.+), (.+)-id=(.+)><>(.+):.+
  name: kafka_streams_stream_state_metrics
  labels:
    thread_id: "$1"
    task_id: "$2"
    partition_id: "$3"
    store_type: "$4"
    state_id: "$5"
    metric: "$6"
- pattern: kafka.streams<type=stream-thread-metrics, thread-id=(.+)><>(.+):.+
  name: kafka_streams_stream_thread_metrics_$2
  labels:
    thread_id: "$1"
- pattern: kafka.streams<type=stream-task-metrics, thread-id=(.*), task-id=(.+)_(.+)><>(.+):.+
  name: kafka_streams_stream_task_metrics_$4
  labels:
    thread_id: "$1"
    task_id: "$2"
    partition_id: "$3"
- pattern: kafka.streams<type=stream-processor-node-metrics, thread-id=(.*), task-id=(.+)_(.+), processor-node-id=(.+)><>(.+):.+
  name: kafka_streams_stream_processor_node_metrics_$5
  labels:
    thread_id: "$1"
    task_id: "$2"
    partition_id: "$3"
    processor_node_id: "$4"
- pattern: kafka.producer<type=producer-metrics, client-id=(.+)><>(.+):.+
  name: kafka_producer_producer_metrics_$2
  labels:
    client_id: "$1"
- pattern: kafka.consumer<type=consumer-metrics, client-id=(.+)><>(.+):.+
  name: kafka_consumer_consumer_metrics_$2
  labels:
    client_id: "$1"
#- pattern: kafka.(.*)


